adventureworks:
  target: postgres # leave this as duckdb, or change this to your chosen database

  # supported databases: duckdb, postgres 
  outputs:
    duckdb: 
     type: duckdb
     path: target/adventureworks.duckdb
     threads: 12

    postgres:  
      type: postgres
      host: localhost
      user: postgres
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: 5430 # 5430 -> 5432
      dbname: adventureworks # create this empty database beforehand 
      schema: dbo
      threads: 12
